function docsHub() {
  const repo = (name) => `https://github.com/ApeWorX/${name}`;
  const readme = (name) => `${repo(name)}#readme`;

  const packages = [
    {
      name: "Ape Framework",
      category: "Core",
      status: "Docs",
      description:
        "Build, test, script, deploy, and explore on-chain with Python.",
      docs: "https://docs.apeworx.io/ape/",
      repo: repo("ape"),
      tags: ["contracts", "testing", "plugins"],
    },
    {
      name: "Silverback",
      category: "Core",
      status: "Docs",
      description:
        "Listen and respond to on-chain events in real time with Python bots.",
      docs: "https://docs.apeworx.io/silverback/",
      repo: repo("silverback"),
      tags: ["bots", "automation", "events"],
    },
    {
      name: "web3.py",
      category: "Core",
      status: "Read the Docs",
      description:
        "Python interface for interacting with Ethereum and EVM-compatible chains.",
      docs: "https://web3py.readthedocs.io/",
      repo: repo("web3.py"),
      tags: ["rpc", "contracts", "providers"],
    },
    {
      name: "eth-account",
      category: "Libraries",
      status: "Read the Docs",
      description:
        "Account abstraction, transaction signing, message signing, and typed data support.",
      docs: "https://eth-account.readthedocs.io/",
      repo: repo("eth-account"),
      tags: ["accounts", "signing", "eip712"],
    },
    {
      name: "eth-abi",
      category: "Libraries",
      status: "Read the Docs",
      description: "Encoding and decoding utilities for the Ethereum ABI.",
      docs: "https://eth-abi.readthedocs.io/",
      repo: repo("eth-abi"),
      tags: ["abi", "encoding", "decoding"],
    },
    {
      name: "eth-bloom",
      category: "Libraries",
      status: "README",
      description: "Ethereum bloom filter implementation.",
      docs: readme("eth-bloom"),
      repo: repo("eth-bloom"),
      tags: ["bloom", "filters", "ethereum"],
    },
    {
      name: "eth-keyfile",
      category: "Libraries",
      status: "README",
      description: "Tools for handling encrypted Ethereum keyfiles.",
      docs: readme("eth-keyfile"),
      repo: repo("eth-keyfile"),
      tags: ["keys", "accounts", "encryption"],
    },
    {
      name: "eth-keys",
      category: "Libraries",
      status: "README",
      description: "Common API for Ethereum key operations.",
      docs: readme("eth-keys"),
      repo: repo("eth-keys"),
      tags: ["keys", "signing", "cryptography"],
    },
    {
      name: "eth-rlp",
      category: "Libraries",
      status: "README",
      description: "RLP models and helpers for Ethereum.",
      docs: readme("eth-rlp"),
      repo: repo("eth-rlp"),
      tags: ["rlp", "models", "ethereum"],
    },
    {
      name: "eth-tester",
      category: "Libraries",
      status: "README",
      description: "Tool suite for testing Ethereum applications.",
      docs: readme("eth-tester"),
      repo: repo("eth-tester"),
      tags: ["testing", "ethereum", "python"],
    },
    {
      name: "hexbytes",
      category: "Libraries",
      status: "Read the Docs",
      description:
        "Python bytes subclass that decodes hex and improves console output.",
      docs: "https://hexbytes.readthedocs.io/",
      repo: repo("hexbytes"),
      tags: ["bytes", "hex", "types"],
    },
    {
      name: "py-geth",
      category: "Libraries",
      status: "README",
      description: "Python wrapper for running Go-Ethereum as a subprocess.",
      docs: readme("py-geth"),
      repo: repo("py-geth"),
      tags: ["geth", "node", "testing"],
    },
    {
      name: "py-solc-x",
      category: "Libraries",
      status: "Read the Docs",
      description:
        "Python wrapper and version manager for the Solidity compiler.",
      docs: "https://solcx.readthedocs.io/",
      repo: repo("py-solc-x"),
      tags: ["solidity", "compiler", "solc"],
    },
    {
      name: "py-ssz",
      category: "Libraries",
      status: "README",
      description:
        "Python implementation of Simple Serialize encoding and decoding.",
      docs: readme("py-ssz"),
      repo: repo("py-ssz"),
      tags: ["ssz", "serialization", "ethereum"],
    },
    {
      name: "py-tokenlists",
      category: "Libraries",
      status: "README",
      description: "Uniswap Token Lists implementation in Python.",
      docs: readme("py-tokenlists"),
      repo: repo("py-tokenlists"),
      tags: ["tokens", "uniswap", "lists"],
    },
    {
      name: "py-trie",
      category: "Libraries",
      status: "README",
      description: "Python implementation of the Ethereum trie structure.",
      docs: readme("py-trie"),
      repo: repo("py-trie"),
      tags: ["trie", "ethereum", "data-structures"],
    },
    {
      name: "pyrlp",
      category: "Libraries",
      status: "README",
      description: "Python RLP serialization library.",
      docs: readme("pyrlp"),
      repo: repo("pyrlp"),
      tags: ["rlp", "serialization", "ethereum"],
    },
    {
      name: "blake2b-py",
      category: "Libraries",
      status: "README",
      description: "Blake2b hashing in Rust with Python bindings.",
      docs: readme("blake2b-py"),
      repo: repo("blake2b-py"),
      tags: ["hashing", "rust", "python"],
    },
    {
      name: "EIP-712",
      category: "Libraries",
      status: "Docs",
      description:
        "Message classes for typed structured data hashing and signing in Ethereum.",
      docs: "https://docs.apeworx.io/eip712/",
      repo: repo("eip712"),
      tags: ["typed-data", "signing", "messages"],
    },
    {
      name: "ETH Pydantic Types",
      category: "Libraries",
      status: "Docs",
      description:
        "Pydantic-compatible Ethereum data types shared across ApeWorX packages.",
      docs: "https://docs.apeworx.io/eth-pydantic-types/",
      repo: repo("eth-pydantic-types"),
      tags: ["pydantic", "types", "ethereum"],
    },
    {
      name: "ETHPM Types",
      category: "Libraries",
      status: "README",
      description: "Implementation of Ethereum package metadata models.",
      docs: readme("ethpm-types"),
      repo: repo("ethpm-types"),
      tags: ["metadata", "packages", "pydantic"],
    },
    {
      name: "EVM Trace",
      category: "Libraries",
      status: "README",
      description:
        "Ethereum Virtual Machine transaction tracing models and helpers.",
      docs: readme("evm-trace"),
      repo: repo("evm-trace"),
      tags: ["traces", "debugging", "evm"],
    },
    {
      name: "EVM Chains",
      category: "Libraries",
      status: "README",
      description:
        "Metadata on EVM-compatible chains organized by Ape-style ecosystem and network.",
      docs: readme("evmchains"),
      repo: repo("evmchains"),
      tags: ["chains", "metadata", "networks"],
    },
    {
      name: "sphinx-ape",
      category: "Libraries",
      status: "README",
      description:
        "Sphinx documentation helpers for Ape-based projects and plugins.",
      docs: readme("sphinx-ape"),
      repo: repo("sphinx-ape"),
      tags: ["docs", "sphinx", "ape"],
    },
    {
      name: "ape-alchemy",
      category: "Ape Plugins",
      status: "README",
      description: "Alchemy network provider plugin for Ape.",
      docs: readme("ape-alchemy"),
      repo: repo("ape-alchemy"),
      tags: ["provider", "alchemy", "rpc"],
    },
    {
      name: "ape-arbitrum",
      category: "Ape Plugins",
      status: "README",
      description: "Arbitrum ecosystem plugin for Ape.",
      docs: readme("ape-arbitrum"),
      repo: repo("ape-arbitrum"),
      tags: ["network", "arbitrum", "l2"],
    },
    {
      name: "ape-avalanche",
      category: "Ape Plugins",
      status: "README",
      description: "Avalanche ecosystem plugin for Ape.",
      docs: readme("ape-avalanche"),
      repo: repo("ape-avalanche"),
      tags: ["network", "avalanche", "ecosystem"],
    },
    {
      name: "ape-aws",
      category: "Ape Plugins",
      status: "README",
      description:
        "Ape plugin for AWS-backed blockchain transaction workflows.",
      docs: readme("ape-aws"),
      repo: repo("ape-aws"),
      tags: ["aws", "accounts", "transactions"],
    },
    {
      name: "ape-base",
      category: "Ape Plugins",
      status: "README",
      description: "Base ecosystem plugin for Ape.",
      docs: readme("ape-base"),
      repo: repo("ape-base"),
      tags: ["network", "base", "l2"],
    },
    {
      name: "ape-blast",
      category: "Ape Plugins",
      status: "README",
      description: "Blast ecosystem plugin for Ape.",
      docs: readme("ape-blast"),
      repo: repo("ape-blast"),
      tags: ["network", "blast", "l2"],
    },
    {
      name: "ape-blockscout",
      category: "Ape Plugins",
      status: "README",
      description: "Blockscout explorer plugin for Ape.",
      docs: readme("ape-blockscout"),
      repo: repo("ape-blockscout"),
      tags: ["explorer", "blockscout", "verification"],
    },
    {
      name: "ape-bsc",
      category: "Ape Plugins",
      status: "README",
      description: "BNB Smart Chain ecosystem plugin for Ape.",
      docs: readme("ape-bsc"),
      repo: repo("ape-bsc"),
      tags: ["network", "bsc", "ecosystem"],
    },
    {
      name: "ape-chainstack",
      category: "Ape Plugins",
      status: "README",
      description: "Chainstack network provider plugin for Ape.",
      docs: readme("ape-chainstack"),
      repo: repo("ape-chainstack"),
      tags: ["provider", "chainstack", "rpc"],
    },
    {
      name: "ape-drpc",
      category: "Ape Plugins",
      status: "README",
      description: "dRPC provider plugin for Ape.",
      docs: readme("ape-drpc"),
      repo: repo("ape-drpc"),
      tags: ["provider", "drpc", "rpc"],
    },
    {
      name: "ape-ens",
      category: "Ape Plugins",
      status: "README",
      description: "Ethereum Name Service converter plugin for Ape.",
      docs: readme("ape-ens"),
      repo: repo("ape-ens"),
      tags: ["converter", "ens", "names"],
    },
    {
      name: "ape-erpc",
      category: "Ape Plugins",
      status: "README",
      description: "eRPC provider plugin for Ape.",
      docs: readme("ape-erpc"),
      repo: repo("ape-erpc"),
      tags: ["provider", "erpc", "rpc"],
    },
    {
      name: "ape-etherscan",
      category: "Ape Plugins",
      status: "README",
      description: "Etherscan explorer plugin for Ape and EVM-based networks.",
      docs: readme("ape-etherscan"),
      repo: repo("ape-etherscan"),
      tags: ["explorer", "verification", "etherscan"],
    },
    {
      name: "ape-fantom",
      category: "Ape Plugins",
      status: "README",
      description: "Fantom ecosystem plugin for Ape.",
      docs: readme("ape-fantom"),
      repo: repo("ape-fantom"),
      tags: ["network", "fantom", "ecosystem"],
    },
    {
      name: "ape-flashbots",
      category: "Ape Plugins",
      status: "README",
      description: "Flashbots network provider plugin for Ape.",
      docs: readme("ape-flashbots"),
      repo: repo("ape-flashbots"),
      tags: ["provider", "flashbots", "mev"],
    },
    {
      name: "ape-foundry",
      category: "Ape Plugins",
      status: "README",
      description: "Foundry network provider plugin for Ape.",
      docs: readme("ape-foundry"),
      repo: repo("ape-foundry"),
      tags: ["provider", "foundry", "testing"],
    },
    {
      name: "ape-hardhat",
      category: "Ape Plugins",
      status: "README",
      description: "Hardhat network provider plugin for Ape.",
      docs: readme("ape-hardhat"),
      repo: repo("ape-hardhat"),
      tags: ["provider", "hardhat", "testing"],
    },
    {
      name: "ape-hyperliquid",
      category: "Ape Plugins",
      status: "README",
      description: "HyperEVM plugin for Ape.",
      docs: readme("ape-hyperliquid"),
      repo: repo("ape-hyperliquid"),
      tags: ["network", "hyperevm", "hyperliquid"],
    },
    {
      name: "ape-infura",
      category: "Ape Plugins",
      status: "README",
      description: "Infura network provider plugin for Ape.",
      docs: readme("ape-infura"),
      repo: repo("ape-infura"),
      tags: ["provider", "infura", "rpc"],
    },
    {
      name: "ape-ledger",
      category: "Ape Plugins",
      status: "README",
      description: "Ledger hardware wallet account plugin for Ape.",
      docs: readme("ape-ledger"),
      repo: repo("ape-ledger"),
      tags: ["accounts", "ledger", "hardware-wallet"],
    },
    {
      name: "ape-notebook",
      category: "Ape Plugins",
      status: "README",
      description: "Jupyter Notebook integration for Ape projects.",
      docs: readme("ape-notebook"),
      repo: repo("ape-notebook"),
      tags: ["notebook", "jupyter", "development"],
    },
    {
      name: "ape-optimism",
      category: "Ape Plugins",
      status: "README",
      description: "Optimism network provider plugin for Ape.",
      docs: readme("ape-optimism"),
      repo: repo("ape-optimism"),
      tags: ["network", "optimism", "l2"],
    },
    {
      name: "ape-polygon",
      category: "Ape Plugins",
      status: "README",
      description: "Polygon ecosystem plugin for Ape.",
      docs: readme("ape-polygon"),
      repo: repo("ape-polygon"),
      tags: ["network", "polygon", "ecosystem"],
    },
    {
      name: "ape-polygon-zkevm",
      category: "Ape Plugins",
      status: "README",
      description: "Polygon zkEVM ecosystem plugin for Ape.",
      docs: readme("ape-polygon-zkevm"),
      repo: repo("ape-polygon-zkevm"),
      tags: ["network", "polygon", "zkevm"],
    },
    {
      name: "ape-safe",
      category: "Ape Plugins",
      status: "Docs",
      description:
        "Safe wallet plugin for Ape account and transaction workflows.",
      docs: "https://docs.apeworx.io/ape-safe/",
      repo: repo("ape-safe"),
      tags: ["accounts", "safe", "multisig"],
    },
    {
      name: "ape-solidity",
      category: "Ape Plugins",
      status: "README",
      description: "Solidity compiler plugin for Ape.",
      docs: readme("ape-solidity"),
      repo: repo("ape-solidity"),
      tags: ["compiler", "solidity", "contracts"],
    },
    {
      name: "ape-sonic",
      category: "Ape Plugins",
      status: "README",
      description: "Sonic ecosystem plugin for Ape.",
      docs: readme("ape-sonic"),
      repo: repo("ape-sonic"),
      tags: ["network", "sonic", "ecosystem"],
    },
    {
      name: "ape-template",
      category: "Ape Plugins",
      status: "README",
      description: "Cookiecutter-based project template plugin for Ape.",
      docs: readme("ape-template"),
      repo: repo("ape-template"),
      tags: ["templates", "cookiecutter", "projects"],
    },
    {
      name: "ape-tenderly",
      category: "Ape Plugins",
      status: "README",
      description: "Tenderly network provider plugin for Ape.",
      docs: readme("ape-tenderly"),
      repo: repo("ape-tenderly"),
      tags: ["provider", "tenderly", "debugging"],
    },
    {
      name: "ape-titanoboa",
      category: "Ape Plugins",
      status: "README",
      description: "Titanoboa integration and pytest runner for Ape.",
      docs: readme("ape-titanoboa"),
      repo: repo("ape-titanoboa"),
      tags: ["vyper", "testing", "titanoboa"],
    },
    {
      name: "ape-tokens",
      category: "Ape Plugins",
      status: "README",
      description: "Token converter plugin for Ape.",
      docs: readme("ape-tokens"),
      repo: repo("ape-tokens"),
      tags: ["converter", "tokens", "erc20"],
    },
    {
      name: "ape-trezor",
      category: "Ape Plugins",
      status: "README",
      description: "Trezor hardware wallet account plugin for Ape.",
      docs: readme("ape-trezor"),
      repo: repo("ape-trezor"),
      tags: ["accounts", "trezor", "hardware-wallet"],
    },
    {
      name: "ape-vyper",
      category: "Ape Plugins",
      status: "README",
      description: "Vyper compiler plugin for Ape.",
      docs: readme("ape-vyper"),
      repo: repo("ape-vyper"),
      tags: ["compiler", "vyper", "contracts"],
    },
    {
      name: "aave-sdk",
      category: "Ape SDKs",
      status: "README",
      description: "Ape SDK for Aave protocols.",
      docs: readme("aave-sdk"),
      repo: repo("aave-sdk"),
      tags: ["aave", "sdk", "defi"],
    },
    {
      name: "createx-py",
      category: "Ape SDKs",
      status: "README",
      description: "Ape-based SDK for deterministic deployments with CreateX.",
      docs: readme("createx-py"),
      repo: repo("createx-py"),
      tags: ["createx", "deployments", "sdk"],
    },
    {
      name: "uniswap-sdk",
      category: "Ape SDKs",
      status: "README",
      description: "Ape SDK for the Uniswap protocol.",
      docs: readme("uniswap-sdk"),
      repo: repo("uniswap-sdk"),
      tags: ["uniswap", "sdk", "defi"],
    },
  ];

  return {
    menuOpen: false,
    query: "",
    selectedCategory: "All",
    packages,
    categories: ["All", "Core", "Ape Plugins", "Ape SDKs", "Libraries"],
    filteredPackages() {
      const query = this.query.trim().toLowerCase();

      return this.packages.filter((pkg) => {
        const categoryMatches =
          this.selectedCategory === "All" ||
          pkg.category === this.selectedCategory;
        const haystack = [
          pkg.name,
          pkg.category,
          pkg.status,
          pkg.description,
          pkg.docs,
          pkg.repo,
          ...pkg.tags,
        ]
          .join(" ")
          .toLowerCase();

        return categoryMatches && (!query || haystack.includes(query));
      });
    },
  };
}
